// Code generated by mockery v2.42.0. DO NOT EDIT.

package mocks

import (
	time "time"

	mock "github.com/stretchr/testify/mock"

	token "gopsql/banking/token"
)

// TokenMaker is an autogenerated mock type for the TokenMaker type
type TokenMaker struct {
	mock.Mock
}

type TokenMaker_Expecter struct {
	mock *mock.Mock
}

func (_m *TokenMaker) EXPECT() *TokenMaker_Expecter {
	return &TokenMaker_Expecter{mock: &_m.Mock}
}

// CreateToken provides a mock function with given fields: _a0, _a1
func (_m *TokenMaker) CreateToken(_a0 string, _a1 time.Duration) (string, error) {
	ret := _m.Called(_a0, _a1)

	if len(ret) == 0 {
		panic("no return value specified for CreateToken")
	}

	var r0 string
	var r1 error
	if rf, ok := ret.Get(0).(func(string, time.Duration) (string, error)); ok {
		return rf(_a0, _a1)
	}
	if rf, ok := ret.Get(0).(func(string, time.Duration) string); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(string)
	}

	if rf, ok := ret.Get(1).(func(string, time.Duration) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenMaker_CreateToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateToken'
type TokenMaker_CreateToken_Call struct {
	*mock.Call
}

// CreateToken is a helper method to define mock.On call
//   - _a0 string
//   - _a1 time.Duration
func (_e *TokenMaker_Expecter) CreateToken(_a0 interface{}, _a1 interface{}) *TokenMaker_CreateToken_Call {
	return &TokenMaker_CreateToken_Call{Call: _e.mock.On("CreateToken", _a0, _a1)}
}

func (_c *TokenMaker_CreateToken_Call) Run(run func(_a0 string, _a1 time.Duration)) *TokenMaker_CreateToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(time.Duration))
	})
	return _c
}

func (_c *TokenMaker_CreateToken_Call) Return(_a0 string, _a1 error) *TokenMaker_CreateToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenMaker_CreateToken_Call) RunAndReturn(run func(string, time.Duration) (string, error)) *TokenMaker_CreateToken_Call {
	_c.Call.Return(run)
	return _c
}

// VerifyToken provides a mock function with given fields: _a0
func (_m *TokenMaker) VerifyToken(_a0 string) (*token.Payload, error) {
	ret := _m.Called(_a0)

	if len(ret) == 0 {
		panic("no return value specified for VerifyToken")
	}

	var r0 *token.Payload
	var r1 error
	if rf, ok := ret.Get(0).(func(string) (*token.Payload, error)); ok {
		return rf(_a0)
	}
	if rf, ok := ret.Get(0).(func(string) *token.Payload); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*token.Payload)
		}
	}

	if rf, ok := ret.Get(1).(func(string) error); ok {
		r1 = rf(_a0)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

// TokenMaker_VerifyToken_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'VerifyToken'
type TokenMaker_VerifyToken_Call struct {
	*mock.Call
}

// VerifyToken is a helper method to define mock.On call
//   - _a0 string
func (_e *TokenMaker_Expecter) VerifyToken(_a0 interface{}) *TokenMaker_VerifyToken_Call {
	return &TokenMaker_VerifyToken_Call{Call: _e.mock.On("VerifyToken", _a0)}
}

func (_c *TokenMaker_VerifyToken_Call) Run(run func(_a0 string)) *TokenMaker_VerifyToken_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *TokenMaker_VerifyToken_Call) Return(_a0 *token.Payload, _a1 error) *TokenMaker_VerifyToken_Call {
	_c.Call.Return(_a0, _a1)
	return _c
}

func (_c *TokenMaker_VerifyToken_Call) RunAndReturn(run func(string) (*token.Payload, error)) *TokenMaker_VerifyToken_Call {
	_c.Call.Return(run)
	return _c
}

// NewTokenMaker creates a new instance of TokenMaker. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewTokenMaker(t interface {
	mock.TestingT
	Cleanup(func())
}) *TokenMaker {
	mock := &TokenMaker{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
